### ISSUE TITLE
compile error while using libconfig installed in /usr

### ISSUE THREAD

**Issue by zhupengjia** [asymmetry/g2psim#4]
The error messages are:
Generating dictionary G2PSim_Dict.cxx ......
Compiling Main.cc ......
# error "You need a ISO C conforming compiler to use the glibc headers"

Error: Missing one of '
\/' expected at or after line 97.
Error: Unexpected end of file (G__fgetstream():2) /usr/include/sys/cdefs.h:436:
Error: Symbol extern"C"{#define __need_size_t#define __need_NULL#include<stddef is not defined in current scope  /usr/include/stdio.h:44:
Error: Failed to evaluate extern"C"{#define __need_size_t#define __need_NULL#include<stddef.h>#include<bits/types
Error: Failed to evaluate extern"C"{#define __need_size_t#define __need_NULL#include<stddef.h>#include<bits/types.h>#define __need_FILE#define __need___FILE#endif#if!defined __FILE_defined&&defined __need_FILE struct _IO_FILE
Error: Symbol __BEGIN_NAMESPACE_STD typedef struct _IO_FILE FILE is not defined in current scope  /usr/include/stdio.h:48:
Error: Missing one of '{' expected at or after line 90.
Error: Unexpected end of file (G__fignorestream():3) /usr/include/stdio.h:947:
Error: Missing one of '{' expected at or after line 517.
Error: Unexpected end of file (G__fignorestream():3) /usr/include/string.h:646:
Error: Symbol div_t is not defined in current scope  /usr/include/stdlib.h:101:
Error: Symbol lldiv_t is not defined in current scope  /usr/include/stdlib.h:121:
Error: Missing one of '{' expected at or after line 466.
Error: Unexpected end of file (G__fignorestream():3) /usr/include/stdlib.h:970:
Error: Missing whitespace at or after line 489.
Error: Unexpected end of file (G__fgetspace():2) /usr/include/math.h:492:
Report: Unrecognized string '__END_DECLS' ignored /usr/include/math.h:493:
Warning: Error occurred during reading source files
Warning: Error occurred during dictionary source generation
!!!Removing G2PSim_Dict.cxx G2PSim_Dict.h !!!
Error: /opt/root/bin/rootcint: error loading headers...
Makefile:203: recipe for target 'G2PSim_Dict.cxx' failed
make: **\* [G2PSim_Dict.cxx] Error 1

solution:
comment sentence below in Makefile and everything works fine:
INCDIRS     += -I$(LIBCONFIG)/include

**Comment by asymmetry** [comment]
It seems that -I/usr will occasionally break the generating of the dictionary file g2psim_dict.cxx by rootcint. Not sure if this is an upstream issue of ROOT. This issue is fixed in commit 7167ae7ff786897d400dea46a67f3e41b9be0610 by adding a test in the Makefile. CLOSED
